// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// countC
NumericVector countC(NumericVector cub, NumericVector cua);
RcppExport SEXP _wassdda_countC(SEXP cubSEXP, SEXP cuaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cub(cubSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cua(cuaSEXP);
    rcpp_result_gen = Rcpp::wrap(countC(cub, cua));
    return rcpp_result_gen;
END_RCPP
}
// stl_sort
NumericVector stl_sort(NumericVector x);
RcppExport SEXP _wassdda_stl_sort(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(stl_sort(x));
    return rcpp_result_gen;
END_RCPP
}
// DW2_discr_C
double DW2_discr_C(NumericVector a, NumericVector b, NumericVector wa, NumericVector wb);
RcppExport SEXP _wassdda_DW2_discr_C(SEXP aSEXP, SEXP bSEXP, SEXP waSEXP, SEXP wbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wa(waSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wb(wbSEXP);
    rcpp_result_gen = Rcpp::wrap(DW2_discr_C(a, b, wa, wb));
    return rcpp_result_gen;
END_RCPP
}
// dmatC
NumericMatrix dmatC(DataFrame T);
RcppExport SEXP _wassdda_dmatC(SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type T(TSEXP);
    rcpp_result_gen = Rcpp::wrap(dmatC(T));
    return rcpp_result_gen;
END_RCPP
}
// dmatC2
NumericMatrix dmatC2(DataFrame T);
RcppExport SEXP _wassdda_dmatC2(SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type T(TSEXP);
    rcpp_result_gen = Rcpp::wrap(dmatC2(T));
    return rcpp_result_gen;
END_RCPP
}
// DiToCen_C
NumericMatrix DiToCen_C(DataFrame Tib, DataFrame Cen, int n, int p, int k);
RcppExport SEXP _wassdda_DiToCen_C(SEXP TibSEXP, SEXP CenSEXP, SEXP nSEXP, SEXP pSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type Tib(TibSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type Cen(CenSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(DiToCen_C(Tib, Cen, n, p, k));
    return rcpp_result_gen;
END_RCPP
}
// TransposeTib_C
List TransposeTib_C(DataFrame Tib);
RcppExport SEXP _wassdda_TransposeTib_C(SEXP TibSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type Tib(TibSEXP);
    rcpp_result_gen = Rcpp::wrap(TransposeTib_C(Tib));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wassdda_countC", (DL_FUNC) &_wassdda_countC, 2},
    {"_wassdda_stl_sort", (DL_FUNC) &_wassdda_stl_sort, 1},
    {"_wassdda_DW2_discr_C", (DL_FUNC) &_wassdda_DW2_discr_C, 4},
    {"_wassdda_dmatC", (DL_FUNC) &_wassdda_dmatC, 1},
    {"_wassdda_dmatC2", (DL_FUNC) &_wassdda_dmatC2, 1},
    {"_wassdda_DiToCen_C", (DL_FUNC) &_wassdda_DiToCen_C, 5},
    {"_wassdda_TransposeTib_C", (DL_FUNC) &_wassdda_TransposeTib_C, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_wassdda(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
