# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countC <- function(cub, cua) {
    .Call('_wassdda_countC', PACKAGE = 'wassdda', cub, cua)
}

stl_sort <- function(x) {
    .Call('_wassdda_stl_sort', PACKAGE = 'wassdda', x)
}

DW2_discr_C <- function(a, b, wa, wb) {
    .Call('_wassdda_DW2_discr_C', PACKAGE = 'wassdda', a, b, wa, wb)
}

dmatC <- function(T) {
    .Call('_wassdda_dmatC', PACKAGE = 'wassdda', T)
}

dmatC2 <- function(T) {
    .Call('_wassdda_dmatC2', PACKAGE = 'wassdda', T)
}

DiToCen_C <- function(Tib, Cen, n, p, k) {
    .Call('_wassdda_DiToCen_C', PACKAGE = 'wassdda', Tib, Cen, n, p, k)
}

TransposeTib_C <- function(Tib) {
    .Call('_wassdda_TransposeTib_C', PACKAGE = 'wassdda', Tib)
}

